FROM python:3.12

WORKDIR /app

RUN pip install gunicorn==25.3.0

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["python", "manage.py", "runserver", "0:8000"]
